apiVersion: v1
kind: ConfigMap
metadata:
  name: astra-config
  namespace: astra-rag
data:
  OPENAI_MODEL: "gpt-4o-mini"
  MODEL_NAME: "llama-3.3-70b-versatile"
  MODEL_TEMPERATURE: "0.2"
  BACKEND_BASE_URL: "http://astra-backend-service:8000"
  CREWAI_TRACING_ENABLED: "false"
