apiVersion: apps/v1
kind: Deployment
metadata:
  name: astra-backend
  namespace: astra-rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: astra-backend
  template:
    metadata:
      labels:
        app: astra-backend
    spec:
      containers:
        - name: astra-backend
          image: hbhangale3/astra-rag:latest
          imagePullPolicy: Always
          command: ["bash", "run_astra.sh"]
          ports:
            - containerPort: 8000
          env:
            - name: MODE
              value: "backend"

            - name: PYTHONPATH
              value: "/app"

            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: astra-secrets
                  key: OPENAI_API_KEY

            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: astra-secrets
                  key: GROQ_API_KEY

            - name: OPENAI_MODEL
              valueFrom:
                configMapKeyRef:
                  name: astra-config
                  key: OPENAI_MODEL

            - name: MODEL_NAME
              valueFrom:
                configMapKeyRef:
                  name: astra-config
                  key: MODEL_NAME

            - name: MODEL_TEMPERATURE
              valueFrom:
                configMapKeyRef:
                  name: astra-config
                  key: MODEL_TEMPERATURE

            - name: CREWAI_TRACING_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: astra-config
                  key: CREWAI_TRACING_ENABLED

          volumeMounts:
            - name: astra-data
              mountPath: /app/data

      volumes:
        - name: astra-data
          persistentVolumeClaim:
            claimName: astra-data-pvc
