apiVersion: v1
kind: Service
metadata:
  name: astra-backend-service
  namespace: astra-rag
spec:
  type: NodePort
  selector:
    app: astra-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
