import time
from typing import Callable

from fastapi import Request, Response
from prometheus_client import Counter, Histogram, Gauge, generate_latest, CONTENT_TYPE_LATEST


api_requests_total = Counter(
    "api_requests_total",
    "Total number of API requests received by the FastAPI backend.",
    ["method", "endpoint", "status_code"],
)

api_errors_total = Counter(
    "api_errors_total",
    "Total number of failed API requests returned by the FastAPI backend.",
    ["method", "endpoint", "status_code"],
)

api_request_latency_seconds = Histogram(
    "api_request_latency_seconds",
    "Latency of FastAPI requests in seconds.",
    ["method", "endpoint"],
)
documents_uploaded_total = Counter(
    "documents_uploaded_total",
    "Total number of documents successfully uploaded.",
    ["user_id"],
)

storage_used_bytes = Gauge(
    "storage_used_bytes",
    "Current storage used by a user in bytes.",
    ["user_id"],
)

chat_requests_total = Counter(
    "chat_requests_total",
    "Total number of chat requests submitted.",
    ["user_id"],
)

quiz_generations_total = Counter(
    "quiz_generations_total",
    "Total number of quiz generation requests submitted.",
    ["user_id"],
)

ingestion_success_total = Counter(
    "ingestion_success_total",
    "Total number of successful document ingestion operations.",
    ["user_id"],
)

ingestion_failure_total = Counter(
    "ingestion_failure_total",
    "Total number of failed document ingestion operations.",
    ["user_id"],
)

rag_retrieval_latency_seconds = Histogram(
    "rag_retrieval_latency_seconds",
    "Latency of RAG retrieval operations in seconds.",
    ["user_id"],
)

llm_generation_latency_seconds = Histogram(
    "llm_generation_latency_seconds",
    "Latency of LLM generation operations in seconds.",
    ["user_id", "model"],
)

llm_input_tokens_total = Counter(
    "llm_input_tokens_total",
    "Total number of input tokens used by LLM calls.",
    ["user_id", "model"],
)

llm_output_tokens_total = Counter(
    "llm_output_tokens_total",
    "Total number of output tokens generated by LLM calls.",
    ["user_id", "model"],
)


def get_metrics_response() -> Response:
    """
    Returns Prometheus metrics in text exposition format.

    Returns:
        Response: FastAPI response containing all registered Prometheus metrics.
    """
    return Response(
        content=generate_latest(),
        media_type=CONTENT_TYPE_LATEST,
    )


async def prometheus_metrics_middleware(
    request: Request,
    call_next: Callable,
):
    """
    Measures request count, error count, and latency for all FastAPI endpoints.

    Parameters:
        request (Request): Incoming FastAPI request.
        call_next (Callable): Next middleware or route handler.

    Returns:
        Response: API response after recording Prometheus metrics.
    """
    start_time = time.time()

    method = request.method
    endpoint = request.url.path
    if endpoint in ["/metrics", "/favicon.ico"]:
        return await call_next(request)


    try:
        response = await call_next(request)
        status_code = str(response.status_code)

        api_requests_total.labels(
            method=method,
            endpoint=endpoint,
            status_code=status_code,
        ).inc()

        if response.status_code >= 400:
            api_errors_total.labels(
                method=method,
                endpoint=endpoint,
                status_code=status_code,
            ).inc()

        return response

    except Exception:
        status_code = "500"

        api_requests_total.labels(
            method=method,
            endpoint=endpoint,
            status_code=status_code,
        ).inc()

        api_errors_total.labels(
            method=method,
            endpoint=endpoint,
            status_code=status_code,
        ).inc()

        raise

    finally:
        duration = time.time() - start_time

        api_request_latency_seconds.labels(
            method=method,
            endpoint=endpoint,
        ).observe(duration)